// Generated by gencpp from file conti_radar/radar_msgs.msg
// DO NOT EDIT!


#ifndef CONTI_RADAR_MESSAGE_RADAR_MSGS_H
#define CONTI_RADAR_MESSAGE_RADAR_MSGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conti_radar
{
template <class ContainerAllocator>
struct radar_msgs_
{
  typedef radar_msgs_<ContainerAllocator> Type;

  radar_msgs_()
    : object_ID(0)
    , x(0.0)
    , y(0.0)
    , velx(0.0)
    , vely(0.0)  {
    }
  radar_msgs_(const ContainerAllocator& _alloc)
    : object_ID(0)
    , x(0.0)
    , y(0.0)
    , velx(0.0)
    , vely(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _object_ID_type;
  _object_ID_type object_ID;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _velx_type;
  _velx_type velx;

   typedef float _vely_type;
  _vely_type vely;





  typedef boost::shared_ptr< ::conti_radar::radar_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conti_radar::radar_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct radar_msgs_

typedef ::conti_radar::radar_msgs_<std::allocator<void> > radar_msgs;

typedef boost::shared_ptr< ::conti_radar::radar_msgs > radar_msgsPtr;
typedef boost::shared_ptr< ::conti_radar::radar_msgs const> radar_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conti_radar::radar_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conti_radar::radar_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conti_radar::radar_msgs_<ContainerAllocator1> & lhs, const ::conti_radar::radar_msgs_<ContainerAllocator2> & rhs)
{
  return lhs.object_ID == rhs.object_ID &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.velx == rhs.velx &&
    lhs.vely == rhs.vely;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conti_radar::radar_msgs_<ContainerAllocator1> & lhs, const ::conti_radar::radar_msgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conti_radar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conti_radar::radar_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conti_radar::radar_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conti_radar::radar_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conti_radar::radar_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conti_radar::radar_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conti_radar::radar_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conti_radar::radar_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "877f9ca9fe90682b5f51d194a8ed2ce9";
  }

  static const char* value(const ::conti_radar::radar_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x877f9ca9fe90682bULL;
  static const uint64_t static_value2 = 0x5f51d194a8ed2ce9ULL;
};

template<class ContainerAllocator>
struct DataType< ::conti_radar::radar_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conti_radar/radar_msgs";
  }

  static const char* value(const ::conti_radar::radar_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conti_radar::radar_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 object_ID\n"
"float32 x\n"
"float32 y\n"
"float32 velx\n"
"float32 vely\n"
;
  }

  static const char* value(const ::conti_radar::radar_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conti_radar::radar_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_ID);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.velx);
      stream.next(m.vely);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conti_radar::radar_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conti_radar::radar_msgs_<ContainerAllocator>& v)
  {
    s << indent << "object_ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.object_ID);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "velx: ";
    Printer<float>::stream(s, indent + "  ", v.velx);
    s << indent << "vely: ";
    Printer<float>::stream(s, indent + "  ", v.vely);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTI_RADAR_MESSAGE_RADAR_MSGS_H
