(cl:in-package conti_radar-msg)
(cl:export '(ID-VAL
          ID
          F_DISTX-VAL
          F_DISTX
          F_DISTY-VAL
          F_DISTY
          F_VRELX-VAL
          F_VRELX
          F_VRELY-VAL
          F_VRELY
          F_ARELX-VAL
          F_ARELX
          F_ARELY-VAL
          F_ARELY
          F_DISTXSTD-VAL
          F_DISTXSTD
          F_DISTYSTD-VAL
          F_DISTYSTD
          F_VRELXSTD-VAL
          F_VRELXSTD
          F_VRELYSTD-VAL
          F_VRELYSTD
          F_ARELXSTD-VAL
          F_ARELXSTD
          F_ARELYSTD-VAL
          F_ARELYSTD
          F_LDELTAX_LEFT-VAL
          F_LDELTAX_LEFT
          F_LDELTAX_MID-VAL
          F_LDELTAX_MID
          F_LDELTAX_RIGHT-VAL
          F_LDELTAX_RIGHT
          F_LDELTAY_LEFT-VAL
          F_LDELTAY_LEFT
          F_LDELTAY_MID-VAL
          F_LDELTAY_MID
          F_LDELTAY_RIGHT-VAL
          F_LDELTAY_RIGHT
          F_RCS-VAL
          F_RCS
          F_OBJECTSCORE-VAL
          F_OBJECTSCORE
          F_VABSX-VAL
          F_VABSX
          F_VABSY-VAL
          F_VABSY
          F_AABSX-VAL
          F_AABSX
          F_AABSY-VAL
          F_AABSY
          F_VABSXSTD-VAL
          F_VABSXSTD
          F_VABSYSTD-VAL
          F_VABSYSTD
          F_AABSXSTD-VAL
          F_AABSXSTD
          F_AABSYSTD-VAL
          F_AABSYSTD
          F_ORIENTATION-VAL
          F_ORIENTATION
          F_ORIENTATIONSTD-VAL
          F_ORIENTATIONSTD
          F_DISTZ-VAL
          F_DISTZ
          F_DISTZSTD-VAL
          F_DISTZSTD
))